# ==============================================================================
# File: scint_analysis/configs/bursts/wilhelm.yaml
# ==============================================================================
# Link to the telescope config and input data
burst_id: "oran"
input_data_path: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/dsa110-scat/scintillation/scint_analysis/data/oran.npz" 
telescope: "dsa" 

# Set all analysis parameters
analysis:
  rfi_masking:
    find_burst_thres: 5.0
    use_symmetric_noise_window: true
    #off_burst_buffer: 100 # uncomment if above is false
    rfi_downsample_factor: 16
    enable_time_domain_flagging: false
    time_threshold_sigma: 7.0
    freq_threshold_sigma: 5.0
  acf:
    num_subbands: 4
    max_lag_mhz: 45.0
    use_snr_subbanding: true
  fitting:
    fit_lagrange_mhz: 45.0
    reference_frequency_mhz: 1400.0

# Set pipeline options
pipeline_options:
  log_level: "INFO"
  save_intermediate_steps: true
  cache_directory: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/dsa110-scat/scintillation/scint_analysis/data/cache"
