# ==============================================================================
# File: scint_analysis/configs/bursts/chromatica.yaml
# ==============================================================================
# Link to the telescope config and input data
burst_id: "chromatica"
input_data_path: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/FLITS/scintillation/data/chromatica.npz" 
telescope: "dsa" 

# Set all analysis parameters
analysis:
  rfi_masking:
    find_burst_thres: 5.0
    # adds 20% total padding to burst envelope
    padding_factor: 0.0
    use_symmetric_noise_window: true
    #off_burst_buffer: 100 # uncomment if above is false
    rfi_downsample_factor: 16
    enable_time_domain_flagging: false
    time_threshold_sigma: 7.0
    freq_threshold_sigma: 5.0
  acf:
    num_subbands: 2
    max_lag_mhz: 45.0
    use_snr_subbanding: false
    enable_intra_pulse_analysis: true
    # Number of time slices
    intra_pulse_time_bins: 5
  fitting:
    fit_lagrange_mhz: 45.0
    reference_frequency_mhz: 1400.0
    # to override BIC model selection
    #force_model: null 
    force_model: 'fit_2c_lor' 
    init_guess:
      # keys must match those in _baseline_registry
      1c_lor:
        l1_gamma1: 0.02
        l1_m1:     0.7
      2c_lor:
        l2_gamma1: 0.02
        l2_gamma2: 0.12
        l2_m1:     0.4
        l2_m2:     0.4
      3c_lor:
        l3_gamma2: 0.08
        l3_gamma3: 0.20
  baseline_subtraction:
    # Set to true to activate this stage
    enable: true 
    # Order of the polynomial to fit (1=linear, 2=quadratic)
    poly_order: 1        
  noise:
    disable: true
    disable_template: true
    template_n_draws: 25
  self_noise:
    disable: true
    
# Set pipeline options
pipeline_options:
  log_level: "INFO"
  save_intermediate_steps: false
  output_plot_path: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/FLITS/scintillation/plots/chromatica_analysis_overview.png"
  cache_directory: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/FLITS/scintillation/data/cache"

  # --- ADD THIS SECTION ---
  diagnostic_plots:
    enable: true
    # Directory where the plots will be saved.
    # This will be created if it doesn't exist.
    directory: "/arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/FLITS/scintillation/plots/diagnostics"