"""Validation thresholds for FLITS fitting."""

from flits.fitting import VALIDATION_THRESHOLDS as VT

# MCMC / Nested Sampling Convergence
MCMC_AUTOCORR_NSTEPS_FACTOR = VT.MCMC_AUTOCORR_NSTEPS_FACTOR
MCMC_BURN_IN_FACTOR = VT.MCMC_BURN_IN_FACTOR
MCMC_ACC_FRAC_MIN = VT.MCMC_ACC_FRAC_MIN
MCMC_ACC_FRAC_MAX = VT.MCMC_ACC_FRAC_MAX
MCMC_MIN_EFFECTIVE_SAMPLES = VT.MCMC_MIN_EFFECTIVE_SAMPLES

# Physical Parameter Bounds
DM_MIN = VT.DM_MIN
DM_MAX = VT.DM_MAX
AMP_MIN = VT.AMP_MIN
AMP_MAX = VT.AMP_MAX  # Increased for bright bursts
WIDTH_MIN = VT.WIDTH_MIN
WIDTH_MAX = VT.WIDTH_MAX

# Likelihood Thresholds
RED_CHI_SQ_CATASTROPHIC = VT.RED_CHI_SQ_CATASTROPHIC

# Residual Validation
RESIDUAL_NORMALITY_PVALUE = VT.RESIDUAL_NORMALITY_PVALUE
RESIDUAL_BIAS_SIGMA_THRESHOLD = VT.RESIDUAL_BIAS_SIGMA_THRESHOLD
RESIDUAL_AUTOCORR_DW_MIN = VT.RESIDUAL_AUTOCORR_DW_MIN
RESIDUAL_AUTOCORR_DW_MAX = VT.RESIDUAL_AUTOCORR_DW_MAX

# Chi-Squared Thresholds
CHI_SQ_RED_EXCELLENT_MIN = VT.CHI_SQ_RED_EXCELLENT_MIN
CHI_SQ_RED_GOOD_MAX = VT.CHI_SQ_RED_GOOD_MAX
CHI_SQ_RED_MARGINAL_MAX = VT.CHI_SQ_RED_MARGINAL_MAX
# CHI_SQ_RED_SUSPICIOUSLY_LOW = 0.3  # Commented out as robust fitting often yields low standard chi2 if errors over-estimated? 
# Actually, consistent with Guide.
CHI_SQ_RED_SUSPICIOUSLY_LOW = VT.CHI_SQ_RED_SUSPICIOUSLY_LOW

# R-Squared Thresholds
R_SQ_EXCELLENT_MIN = VT.R_SQ_EXCELLENT_MIN
R_SQ_GOOD_MIN = VT.R_SQ_GOOD_MIN
R_SQ_MARGINAL_MIN = VT.R_SQ_MARGINAL_MIN
R_SQ_POOR_MIN = VT.R_SQ_POOR_MIN

# Parameter Uncertainty Thresholds
PARAM_UNCERTAINTY_GOOD_MAX = VT.PARAM_UNCERTAINTY_GOOD_MAX
PARAM_UNCERTAINTY_ACCEPTABLE_MAX = VT.PARAM_UNCERTAINTY_ACCEPTABLE_MAX
PARAM_UNCERTAINTY_MARGINAL_MAX = VT.PARAM_UNCERTAINTY_MARGINAL_MAX

# Physics Constraints
TAU_DELTANU_MIN = VT.TAU_DELTANU_MIN
TAU_DELTANU_MAX = VT.TAU_DELTANU_MAX
TAU_DELTANU_THIN_SCREEN = VT.TAU_DELTANU_THIN_SCREEN
TAU_DELTANU_EXTENDED = VT.TAU_DELTANU_EXTENDED

ALPHA_KOLMOGOROV = VT.ALPHA_KOLMOGOROV
ALPHA_GOOD_MIN = VT.ALPHA_GOOD_MIN
ALPHA_GOOD_MAX = VT.ALPHA_GOOD_MAX
ALPHA_MARGINAL_MIN = VT.ALPHA_MARGINAL_MIN
ALPHA_MARGINAL_MAX = VT.ALPHA_MARGINAL_MAX
